Repository UBC-MDS/DSCI-532_2024_6_Green-Development-Planner, pull requests merged in 2024-04, with the labels that each got.

#39 23 dashboard playground branch
  data/preprocessed/preprocessed_data.cpg
  data/preprocessed/preprocessed_data.dbf
  data/preprocessed/preprocessed_data.prj
  data/preprocessed/preprocessed_data.shp
  data/preprocessed/preprocessed_data.shx
  data/preprocessed/processed_data.csv
  data/preprocessed/world.cpg
  data/preprocessed/world.dbf
  data/preprocessed/world.prj
  data/preprocessed/world.shp
  data/preprocessed/world.shx
  environment.yml
  notebooks/eda.ipynb
  notebooks/preprocessing.ipynb
  src/app.py
Labels: enhancement

#46 43 further dashboard enhancements and formatting
  src/app.py
Labels: enhancement

#49 upload demo gif
  img/demo.gif
Labels: documentation

#60 colors labels and titles all refined
  src/app.py
Labels: enhancement

#62 61 milestone3 reflection
  reports/m3-reflection.md
Labels: documentation

#65 53 break app code into multiple files
  src/app.py
  src/assets/styles.css
  src/callbacks/__init__.py
  src/callbacks/barcharts.py
  src/callbacks/cards.py
  src/callbacks/piecharts.py
  src/callbacks/worldmap.py
  src/components/__init__.py
  src/components/cards.py
  src/components/charts.py
  src/components/filters.py
  src/components/footer.py
  src/components/markdowns.py
  src/components/title.py
  src/data/__init__.py
  src/data/data.py
Labels: documentation, enhancement

#67 test automatic update of deployment time in footer
  src/components/footer.py
  src/utils/__init__.py
  src/utils/utils.py
Labels: enhancement

#70 69 bug fixes for callbacks between plots
  src/app.py
  src/callbacks/barcharts.py
  src/callbacks/piecharts.py
  src/components/charts.py
  src/components/footer.py
Labels: bug

#72 remove src prefix from import statements
  src/app.py
Labels: bug

#74 add parent path to reading data
  src/data/data.py
Labels: bug

#79 78 separation of map and charts
  README.md
  src/app.py
  src/callbacks/worldmap.py
  src/components/filters.py
  src/data/data.py
Labels: documentation, enhancement

#81 80 update deployment render link
  README.md
  img/demo.gif
Labels: documentation

#94 remove automatic update of deployment date until bug fixed
  src/components/footer.py
Labels: bug

#114 add pyarrow to requirements
  requirements.txt
Labels: bug

#116 115 final touches and modifications
  README.md
  data/preprocessed/access_to_electricity.parquet
  img/demo.gif
  notebooks/data_preprocess.ipynb
  src/app.py
  src/assets/favicon.ico
  src/callbacks/barcharts.py
  src/callbacks/piecharts.py
  src/callbacks/worldmap.py
  src/components/footer.py
  src/components/subtitle.py
  src/components/title.py
Labels: enhancement
